### PR TITLE
post jwm 16.06.1

### PR DESCRIPTION
**Pull request by holmeslinux**
post edition jwm 16.06.1

### CODE REVIEW

**Comment by oberon2007** [comment]
I've moved the files to manjaro sourceforge and updated the link :)
Is there maybe something you can do about the slightly distorted screenshot? Like now the logo in the middle is not round... ;)

**Comment by holmeslinux** [comment]
hello @oberon2007 
i realized that,
i made images of the vbox.
when in vbox wallpaper is flattened.
strange it!

**Comment by holmeslinux** [comment]
@oberon2007 
i was thinking now.
is is the size of the wallpaper?

**Comment by holmeslinux** [comment]
@oberon2007 
use is image

http://i.imgur.com/JWeuGL5.png

you could change?
i am in my work and have no access to git.

**Pull request merged**
